In [4]:
import numpy as np
a = np.array([1,2,3])
print(a) # creating a single dimension matrix
print(a.shape)
b=np.array([   # creating a two dimension matrix
    [4,5,6],
    [7,8,9]
])
print(b)
print(b.shape) # shape function explains the size of the matrix


[1 2 3]
(3,)
[[4 5 6]
 [7 8 9]]
(2, 3)


In [7]:
c=np.arange(1,5,.1) # start,end,step
print(c)
print(c.shape)
d=np.linspace(1,10,20) #for equal spacing between the elements
print(d)


[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5
 4.6 4.7 4.8 4.9]
(40,)
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [8]:
c.ndim # to check the dimension of the array

1

In [9]:
c.reshape(4,10) # 4 is row and 10 is the column

array([[1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9]])

In [10]:
c.reshape(10,4)

array([[1. , 1.1, 1.2, 1.3],
       [1.4, 1.5, 1.6, 1.7],
       [1.8, 1.9, 2. , 2.1],
       [2.2, 2.3, 2.4, 2.5],
       [2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3],
       [3.4, 3.5, 3.6, 3.7],
       [3.8, 3.9, 4. , 4.1],
       [4.2, 4.3, 4.4, 4.5],
       [4.6, 4.7, 4.8, 4.9]])

In [14]:
np.random.randint(1,100,(3,3))

array([[19, 36,  7],
       [52, 36, 14],
       [62, 98,  4]])

In [15]:
# Mathematical calculations in numpy-
x=np.array([
    [2,3,4],
    [4,5,6]
])
y=np.array([
    [4,3,2],
    [3,5,1]
])

In [18]:
print(x+y)  # matix addition
print(x-y)  # matrix subtraction
print(x*y)  # matrix multiplication
print(x/y)  # matrix division
print(x**y) # matrix exponent operation
print(x%y) # matrix modulus

[[ 6  6  6]
 [ 7 10  7]]
[[-2  0  2]
 [ 1  0  5]]
[[ 8  9  8]
 [12 25  6]]
[[0.5        1.         2.        ]
 [1.33333333 1.         6.        ]]
[[  16   27   16]
 [  64 3125    6]]
[[2 0 0]
 [1 0 0]]


In [22]:
print(x*2)
print(x/2)
print(x**2)
print(x%2)

[[ 4  6  8]
 [ 8 10 12]]
[[1.  1.5 2. ]
 [2.  2.5 3. ]]
[[ 4  9 16]
 [16 25 36]]
[[0 1 0]
 [0 1 0]]


In [23]:
# matrix multiplication
print(x.dot(y.T)) # T for transpose

[[25 25]
 [43 43]]


In [24]:
print(np.matmul(x,y.T)) # Another approach for matrix multiplication using dot product

[[25 25]
 [43 43]]


In [25]:
print(x@y.T) # third approach for matrix multiplication using dot product

[[25 25]
 [43 43]]


In [33]:
# Statistical functions - 
print(x.sum())
print(x.sum(axis=0)) # sum of columns
print(x.sum(axis=1)) # sum of rows
print(x.mean())
print(x.std()) # standard deviation
print(x.min()) # minimum value in matrix
print(x.max())
print(x.argmax()) # maximum element's index
print(x.argmin()) # minimum element's index

24
[ 6  8 10]
[ 9 15]
4.0
1.2909944487358056
2
6
5
0


In [37]:
# trigonometric functions-
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[[ 0.90929743  0.14112001 -0.7568025 ]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[-0.41614684 -0.9899925  -0.65364362]
 [-0.65364362  0.28366219  0.96017029]]
[[-2.18503986 -0.14254654  1.15782128]
 [ 1.15782128 -3.38051501 -0.29100619]]


In [41]:
# indexing -
print(x[0,0]) # first row, first column
print(x[0,:]) # first row,all columns
print(x[:,0]) # all rows,first column
print(x[:2,:2]) # first two rows,first two columns
print(x[:2]) # first two rows

2
[2 3 4]
[2 4]
[[2 3]
 [4 5]]
[[2 3 4]
 [4 5 6]]
